In [3]:
'''_In this script, we ..._'''

'_In this script, we ..._'

In [4]:
# -*- coding: utf-8 -*- #
# Authors: gracecaj@stud.ntnu.no, sbaarak@stud.ntnu.no, & annakale@stud.ntnu.no
# Date: 19/09/2023

In [16]:
#%%
#* Import the code needed
import os
import pandas as pd
from pathlib import Path
import numpy as np
import xarray as xr

In [2]:
#%%
#* Define paths
directory_path = Path('../../')

# Import all the raw datasets

In [7]:
#%%
#* Import all population datasets (READY)

population_1600s = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'Population' / 'raw_pop_1600_1650.xlsx',
    index_col=0)

population_time_series = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'Population' / 'raw_pop_1735_2023.xlsx',
    index_col=0)

population_projections = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'Population' / 'norway_pop_projections.xlsx',
    index_col=0)

#* Display datasets to check how their structure look
print(population_1600s)
print(population_time_series)
print(population_projections)

      Population
Year
1600      400000
1650      450000
                                                              Unnamed: 1
05803: Endringer i befolkningen i løpet av året...
NaN                                                                  NaN
Year                                                Befolkning 1. januar
1735                                                              616109
1736                                                              622197
1737                                                              626986
...                                                                  ...
Database:                                                            NaN
Ekstern PRODUKSJON                                                   NaN
NaN                                                                  NaN
Intern referansekode:                                                NaN
Personer                                                             NaN

[337 rows x 1 columns]
      Folketall  Hovedalternativ (MMM)  Lav nasjonal vekst (LLL)  \
År
1980  4078900.0                    NaN                       NaN
1981  4092340.0                    NaN                       NaN
1982  4107063.0                    NaN                       NaN
1983  4122511.0                    NaN                       NaN
1984  4134353.0                    NaN                       NaN
...         ...                    ...                       ...
2056        NaN              6080222.0                 5270975.0
2057        NaN              6086000.0                 5248581.0
2058        NaN              6091372.0                 5224861.0
2059        NaN              6096426.0                 5200732.0
2060        NaN              6101191.0                 5175762.0

      Høy nasjonal vekst (HHH)
År
1980                       NaN
1981                       NaN
1982                       NaN
1983                       NaN
1984                       NaN
...                        ...
2056                 6918978.0
2057                 6960334.0
2058                 7002244.0
2059                 7044668.0
2060                 7087564.0

[81 rows x 4 columns]

In [8]:
#%%
#* Import all PpD datasets

PpD_2000s = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'PpD' / 'raw_PpD_2000s.xlsx',
    index_col=0, skiprows=[0, 1, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72])

PpD_1900s = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'PpD' / 'raw_PpD_1900s.xlsx',
    index_col=0, skiprows=[0, 1, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55])

PpD_1800s = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'PpD' / 'raw_PpD_1800_1900.xlsx',
    index_col=0)

#* Display datasets to check how their structure look
print(PpD_2000s)
print(PpD_1900s)
print(PpD_1800s)

      Personer per privathusholdning
1960                            3.27
1970                            2.94
1980                            2.66
1990                            2.40
2001                            2.29
2005                            2.27
2006                            2.26
2007                            2.25
2008                            2.23
2009                            2.22
2010                            2.22
2011                            2.22
2012                            2.22
2013                            2.21
2014                            2.20
2015                            2.20
2016                            2.19
2017                            2.19
2018                            2.17
2019                            2.16
2020                            2.15
2021                            2.13
2022                            2.12
2023                            2.11
      Personer per husholdning
Year
1920                      4.30
1930                      3.98
1946                      3.36
1950                      3.25
1960                      3.27
1970                      2.94
1980                      2.66
1990                      2.40
      PpD
Year
1801  5.4
1874  4.7
1900  4.3

In [8]:
#%%
#* Import the UFApD as three seperate datasets for the diff types

UFApD_raw_SFH = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'UFApD' / 'raw_UFApD.xlsx',
    usecols='A, B')

UFApD_raw_TH = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'UFApD' / 'raw_UFApD.xlsx',
    usecols='A, C')

UFApD_raw_AB = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'UFApD' / 'raw_UFApD.xlsx',
    usecols='A, D')

#* Display datasets to check how their structure look
print(UFApD_raw_SFH)
print(UFApD_raw_TH)
print(UFApD_raw_AB)

   Unnamed: 0  SFH
0        1890  254
1        1963  228
2        1975  152
3        1985  123
4        1995  159
5        2005  322
6        2012  184
   Unnamed: 0   TH
0        1890  108
1        1963   99
2        1975  119
3        1985  113
4        1995  101
5        2005  103
6        2012   99
   Unnamed: 0  AB
0        1890  75
1        1963  64
2        1975  94
3        1985  76
4        1995  69
5        2005  76
6        2012  67

In [10]:
#%%
#? Import all Dwelling Lifetime datasets (might not be needed)

In [11]:
#%%
#* Import all Energy Intensity datasets

In [10]:
#%%
#* Import all Carbon Intensity datasets

carbon_intensity_raw = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'Carbon_Intensity' / 'raw_energy_and_carbon_intensity.xlsx',
    sheet_name= 'Sheet2', index_col=[0,1,2], skiprows=[0])

In [13]:
#%%
#* Import all Type Split datasets

type_split = pd.read_excel(
    directory_path / 'data' / 'raw_data' / 'Type_Split' /'raw_type_split.xlsx',
    index_col=0)

#* Display datasets to check how their structure look
print(type_split)

                        Unnamed: 1 Unnamed: 2 Unnamed: 3  \
Number of buildings (#)
Age classes                    SFH         TH         AB
1955 and before            371 183     69 020     26 955
1956 - 1970                209 324     56 769      7 419
1971 - 1980                194 861     49 848      4 546
1981 - 1990                178 291     44 391      5 296
1991 - 2000                 91 914     30 924      6 319
2001 - 2010                 83 819     40 468     10 450
2011 and after              16 695      9 623      2 280
SUM                      1 146 087    301 043     63 265

                        Number of dwellings (#) Unnamed: 5 Unnamed: 6  \
Number of buildings (#)
Age classes                               Total        SFH         TH
1955 and before                         467 158    401 482    143 241
1956 - 1970                             273 512    227 929     81 577
1971 - 1980                             249 255    219 673     72 521
1981 - 1990                             227 978    202 228     70 619
1991 - 2000                             129 157    109 696     55 632
2001 - 2010                             134 737     98 808     67 624
2011 and after                           28 598     19 144     13 929
SUM                                   1 510 395  1 278 960    505 143

                        Unnamed: 7 Utility floor space (1000 m²) Unnamed: 9  \
Number of buildings (#)
Age classes                     AB                         Total        SFH
1955 and before            179 666                       724 389     62 677
1956 - 1970                121 358                       430 864     37 288
1971 - 1980                 91 387                       383 581     37 204
1981 - 1990                 57 471                       330 318     38 202
1991 - 2000                 65 056                       230 384     17 912
2001 - 2010                126 975                       293 407     16 525
2011 and after              23 194                        56 267      3 433
SUM                        665 107                     2 449 210    213 241

                        Unnamed: 10 Unnamed: 11 Unnamed: 12
Number of buildings (#)
Age classes                      TH          AB       Total
1955 and before              14 765      11 816      89 258
1956 - 1970                   9 656       7 614      54 557
1971 - 1980                   8 523       6 565      52 292
1981 - 1990                   8 014       4 300      50 516
1991 - 2000                   5 586       4 437      27 935
2001 - 2010                   6 977       9 006      32 508
2011 and after                1 570       1 866       6 869
SUM                          55 091      45 604     313 936

In [14]:
#%%
#* Import all Renovation datasets

# Clean the datasets as necessary

In [15]:
#* Cleaning the PpD datasets
# standardize the column labels
PpD_2000s = PpD_2000s.rename(columns={'Personer per privathusholdning': 'PpD'})
PpD_1900s = PpD_1900s.rename(columns={'Personer per husholdning': 'PpD'})

# standardize the index names
PpD_2000s.index.name = 'Year'

# drop reduntant datapoints in PpD_2000s
PpD_2000s = PpD_2000s.drop(index=[1960, 1970, 1980, 1990])

# print datasets for quality check
print(PpD_2000s)
print(PpD_1900s)
print(PpD_1800s)

       PpD
Year
2001  2.29
2005  2.27
2006  2.26
2007  2.25
2008  2.23
2009  2.22
2010  2.22
2011  2.22
2012  2.22
2013  2.21
2014  2.20
2015  2.20
2016  2.19
2017  2.19
2018  2.17
2019  2.16
2020  2.15
2021  2.13
2022  2.12
2023  2.11
       PpD
Year
1920  4.30
1930  3.98
1946  3.36
1950  3.25
1960  3.27
1970  2.94
1980  2.66
1990  2.40
      PpD
Year
1801  5.4
1874  4.7
1900  4.3

In [11]:
#* Cleaning UFApD

UFApD_raw_SFH.rename(columns={'Unnamed: 0': 'Year', 'SFH': 'UFApD'}, inplace=True)
UFApD_raw_TH.rename(columns={'Unnamed: 0': 'Year', 'TH': 'UFApD'}, inplace=True)
UFApD_raw_AB.rename(columns={'Unnamed: 0': 'Year', 'AB': 'UFApD'}, inplace=True)

UFApD_raw_SFH = UFApD_raw_SFH.set_index('Year')
UFApD_raw_TH = UFApD_raw_TH.set_index('Year')
UFApD_raw_AB = UFApD_raw_AB.set_index('Year')

print(UFApD_raw_SFH)
print(UFApD_raw_TH)
print(UFApD_raw_AB)

      UFApD
Year
1890    254
1963    228
1975    152
1985    123
1995    159
2005    322
2012    184
      UFApD
Year
1890    108
1963     99
1975    119
1985    113
1995    101
2005    103
2012     99
      UFApD
Year
1890     75
1963     64
1975     94
1985     76
1995     69
2005     76
2012     67

In [27]:
pd.options.display.max_rows = 92

carbon_intensity_raw

                                 Carbon  (kg/m2a)
Cohort    Type Renovation Level
pre 1955  SFH  OG                           80.60
               Reg Refurb                   59.40
               Adv Refurb                    7.20
          TH   OG                           84.70
               Reg Refurb                   61.10
               Adv Refurb                    0.80
          AB   OG                           90.30
               Reg Refurb                   88.70
               Adv Refurb                   13.10
1956-70   SFH  OG                           80.40
               Reg Refurb                   62.30
               Adv Refurb                    7.20
          TH   OG                           74.20
               Reg Refurb                   55.50
               Adv Refurb                    0.25
          AB   OG                          101.90
               Reg Refurb                   52.40
               Adv Refurb                   27.90
1971-80   SFH  OG                           74.30
               Reg Refurb                   54.80
               Adv Refurb                    0.50
          TH   OG                           74.20
               Reg Refurb                   55.10
               Adv Refurb                    1.20
          AB   OG                          103.40
               Reg Refurb                   88.30
               Adv Refurb                   11.40
1981-90   SFH  OG                           80.70
               Reg Refurb                   62.50
               Adv Refurb                    7.20
          TH   OG                           76.40
               Reg Refurb                   53.30
               Adv Refurb                    0.30
          AB   OG                           99.50
               Reg Refurb                   88.30
               Adv Refurb                   12.10
1991-2000 SFH  OG                           89.80
               Reg Refurb                   54.40
               Adv Refurb                   -4.90
          TH   Adv Refurb                     NaN
               OG                           89.90
               Reg Refurb                   53.20
               Adv Refurb                    1.70
          AB   Adv Refurb                     NaN
               OG                          100.90
               Reg Refurb                   88.00
               Adv Refurb                   11.90
2001-2010 SFH  OG                           50.50
               Reg Refurb                   39.90
               Adv Refurb                    1.10
          TH   OG                           80.40
               Reg Refurb                   45.20
               Adv Refurb                    0.00
          AB   OG                           69.80
               Reg Refurb                   40.80
               Adv Refurb                    6.70
2011-     SFH  OG                           61.90
               Reg Refurb                   29.40
               Adv Refurb                   -6.70
          TH   OG                           63.40
               Reg Refurb                   29.70
               Adv Refurb                   -6.40
          AB   OG                           53.30
               Reg Refurb                   30.60
               Adv Refurb                   18.80

# Combine the datasets into one per parameter

In [17]:
#%%
#* Combine the population datasets into one

In [18]:
#%%
#* Combine the PpD datasets into one time series
historical_PpD = pd.concat([PpD_1800s, PpD_1900s,PpD_2000s])

# print for quality check
print(historical_PpD)

       PpD
Year
1801  5.40
1874  4.70
1900  4.30
1920  4.30
1930  3.98
1946  3.36
1950  3.25
1960  3.27
1970  2.94
1980  2.66
1990  2.40
2001  2.29
2005  2.27
2006  2.26
2007  2.25
2008  2.23
2009  2.22
2010  2.22
2011  2.22
2012  2.22
2013  2.21
2014  2.20
2015  2.20
2016  2.19
2017  2.19
2018  2.17
2019  2.16
2020  2.15
2021  2.13
2022  2.12
2023  2.11

# Export the new datasets into the cleaned and combined data folder

In [20]:
historical_PpD.to_excel(directory_path / 
                 'data/cleaned_and_combined_data/PpD/historical_PpD.xlsx')

In [12]:
UFApD_raw_SFH.to_excel(directory_path / 
                 'data/cleaned_and_combined_data/UFApD/historical_UFApD_SFH.xlsx')
UFApD_raw_TH.to_excel(directory_path / 
                 'data/cleaned_and_combined_data/UFApD/historical_UFApD_TH.xlsx')
UFApD_raw_AB.to_excel(directory_path / 
                 'data/cleaned_and_combined_data/UFApD/historical_UFApD_AB.xlsx')

      UFApD
Year
1890    254
1963    228
1975    152
1985    123
1995    159
2005    322
2012    184
      UFApD
Year
1890    108
1963     99
1975    119
1985    113
1995    101
2005    103
2012     99
      UFApD
Year
1890     75
1963     64
1975     94
1985     76
1995     69
2005     76
2012     67

In [ ]:
carbon_intensity_raw.to_excel(directory_path / 
                 'data/cleaned_and_combined_data/Carbon_Intensity/Carbon_Intensity_Constants.xlsx')